#!/usr/bin/env sh

set -eu

ROOT=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
BUILD_DIR="$ROOT/build/local-build"
PREFIX="$ROOT/build/local"

CONFIG_HOME=${XDG_CONFIG_HOME:-"$HOME/.config"}
STATE_HOME=${XDG_STATE_HOME:-"$HOME/.local/state"}
USER_BIN=${XDG_BIN_HOME:-"$HOME/.local/bin"}

CONFIG_DIR="$CONFIG_HOME/quickshell/caelestia"
STATE_DIR="$STATE_HOME/caelestia-shell-switch"
CONFIG_BACKUP="$STATE_DIR/config-backup"
WRAPPER="$USER_BIN/caelestia"
WRAPPER_BACKUP="$STATE_DIR/caelestia-wrapper-backup"
SYSTEM_CLI_FILE="$STATE_DIR/system-cli"
PREFIX_FILE="$STATE_DIR/local-prefix"
WRAPPER_MARKER="Generated by caelestia-shell switch.sh"

stop_caelestia() {
    qs list --all 2>/dev/null | awk '
        /^Instance / {
            id = $2
            sub(/:$/, "", id)
        }
        /^  Config path: / {
            sub(/^  Config path: /, "")
            print id "|" $0
        }
    ' | while IFS='|' read -r id path; do
        if [ "$path" = "$ROOT/shell.qml" ] ||
            [ "$path" = "$CONFIG_DIR/shell.qml" ] ||
            [ "$path" = "/etc/xdg/quickshell/caelestia/shell.qml" ]; then
            qs kill -i "$id" >/dev/null 2>&1 || true
        fi
    done
}

for command in cmake ninja qs; do
    if ! command -v "$command" >/dev/null 2>&1; then
        printf 'Missing required command: %s\n' "$command" >&2
        exit 1
    fi
done

mkdir -p "$STATE_DIR" "$USER_BIN" "$(dirname -- "$CONFIG_DIR")"

if [ -e "$CONFIG_DIR" ] || [ -L "$CONFIG_DIR" ]; then
    current_target=$(readlink -f "$CONFIG_DIR" 2>/dev/null || true)
    if [ "$current_target" != "$ROOT" ] && { [ -e "$CONFIG_BACKUP" ] || [ -L "$CONFIG_BACKUP" ]; }; then
        printf 'Refusing to overwrite the saved config backup at %s\n' "$CONFIG_BACKUP" >&2
        exit 1
    fi
fi

if { [ -e "$WRAPPER" ] || [ -L "$WRAPPER" ]; } &&
    ! grep -qF "$WRAPPER_MARKER" "$WRAPPER" 2>/dev/null &&
    { [ -e "$WRAPPER_BACKUP" ] || [ -L "$WRAPPER_BACKUP" ]; }; then
    printf 'Refusing to overwrite the saved launcher backup at %s\n' "$WRAPPER_BACKUP" >&2
    exit 1
fi

if [ ! -f "$SYSTEM_CLI_FILE" ]; then
    if [ -x /usr/bin/caelestia ]; then
        system_cli=/usr/bin/caelestia
    else
        system_cli=$(command -v caelestia || true)
    fi
    if [ -z "$system_cli" ]; then
        printf 'Could not find the system caelestia CLI.\n' >&2
        exit 1
    fi
    printf '%s\n' "$system_cli" >"$SYSTEM_CLI_FILE"
fi

system_cli=
IFS= read -r system_cli <"$SYSTEM_CLI_FILE"
if [ ! -x "$system_cli" ]; then
    printf 'The saved system Caelestia CLI is not executable: %s\n' "$system_cli" >&2
    exit 1
fi

git_revision=local
if command -v git >/dev/null 2>&1; then
    git_revision=$(git -C "$ROOT" rev-parse --verify HEAD 2>/dev/null || printf 'local')
fi

printf 'Building the local Caelestia plugin...\n'
cmake -S "$ROOT" -B "$BUILD_DIR" -G Ninja \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_INSTALL_PREFIX="$PREFIX" \
    -DVERSION=0.0.0 \
    -DGIT_REVISION="$git_revision" \
    -DDISTRIBUTOR=local-switch \
    -DENABLE_MODULES='extras;plugin'
cmake --build "$BUILD_DIR"
cmake --install "$BUILD_DIR"

if [ -e "$CONFIG_DIR" ] || [ -L "$CONFIG_DIR" ]; then
    current_target=$(readlink -f "$CONFIG_DIR" 2>/dev/null || true)
    if [ "$current_target" != "$ROOT" ]; then
        mv "$CONFIG_DIR" "$CONFIG_BACKUP"
    fi
fi

if [ ! -e "$CONFIG_DIR" ] && [ ! -L "$CONFIG_DIR" ]; then
    ln -s "$ROOT" "$CONFIG_DIR"
fi

if [ -e "$WRAPPER" ] || [ -L "$WRAPPER" ]; then
    if ! grep -qF "$WRAPPER_MARKER" "$WRAPPER" 2>/dev/null; then
        mv "$WRAPPER" "$WRAPPER_BACKUP"
    fi
fi

printf '%s\n' "$PREFIX" >"$PREFIX_FILE"
printf '%s\n' \
    '#!/usr/bin/env sh' \
    "# $WRAPPER_MARKER" \
    'set -eu' \
    'state_home=${XDG_STATE_HOME:-"$HOME/.local/state"}' \
    'state_dir="$state_home/caelestia-shell-switch"' \
    'prefix=' \
    'system_cli=' \
    'IFS= read -r prefix <"$state_dir/local-prefix"' \
    'IFS= read -r system_cli <"$state_dir/system-cli"' \
    'export QML2_IMPORT_PATH="$prefix/lib/qt6/qml${QML2_IMPORT_PATH:+:$QML2_IMPORT_PATH}"' \
    'export CAELESTIA_LIB_DIR="$prefix/lib/caelestia"' \
    'exec "$system_cli" "$@"' \
    >"$WRAPPER"
chmod +x "$WRAPPER"

stop_caelestia
"$WRAPPER" shell -d

printf '\nSwitched to the local checkout:\n  %s\n' "$ROOT"
printf 'Run %s/unswitch.sh to restore the system installation.\n' "$ROOT"
