#!/usr/bin/env sh

set -eu

ROOT=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)

CONFIG_HOME=${XDG_CONFIG_HOME:-"$HOME/.config"}
STATE_HOME=${XDG_STATE_HOME:-"$HOME/.local/state"}
USER_BIN=${XDG_BIN_HOME:-"$HOME/.local/bin"}

CONFIG_DIR="$CONFIG_HOME/quickshell/caelestia"
STATE_DIR="$STATE_HOME/caelestia-shell-switch"
CONFIG_BACKUP="$STATE_DIR/config-backup"
WRAPPER="$USER_BIN/caelestia"
WRAPPER_BACKUP="$STATE_DIR/caelestia-wrapper-backup"
SYSTEM_CLI_FILE="$STATE_DIR/system-cli"
WRAPPER_MARKER="Generated by caelestia-shell switch.sh"

stop_caelestia() {
    qs list --all 2>/dev/null | awk '
        /^Instance / {
            id = $2
            sub(/:$/, "", id)
        }
        /^  Config path: / {
            sub(/^  Config path: /, "")
            print id "|" $0
        }
    ' | while IFS='|' read -r id path; do
        if [ "$path" = "$ROOT/shell.qml" ] ||
            [ "$path" = "$CONFIG_DIR/shell.qml" ] ||
            [ "$path" = "/etc/xdg/quickshell/caelestia/shell.qml" ]; then
            qs kill -i "$id" >/dev/null 2>&1 || true
        fi
    done
}

if [ ! -f "$SYSTEM_CLI_FILE" ]; then
    printf 'No saved system installation was found. Run switch.sh first.\n' >&2
    exit 1
fi

system_cli=
IFS= read -r system_cli <"$SYSTEM_CLI_FILE"
if [ ! -x "$system_cli" ]; then
    printf 'The saved system Caelestia CLI is not executable: %s\n' "$system_cli" >&2
    exit 1
fi

if [ -e "$CONFIG_DIR" ] || [ -L "$CONFIG_DIR" ]; then
    current_target=$(readlink -f "$CONFIG_DIR" 2>/dev/null || true)
    if [ "$current_target" != "$ROOT" ]; then
        printf 'Refusing to replace %s because it is no longer the local checkout link.\n' "$CONFIG_DIR" >&2
        exit 1
    fi
fi

if [ -e "$WRAPPER" ] || [ -L "$WRAPPER" ]; then
    if ! grep -qF "$WRAPPER_MARKER" "$WRAPPER" 2>/dev/null; then
        printf 'Refusing to replace %s because it was not created by switch.sh.\n' "$WRAPPER" >&2
        exit 1
    fi
fi

stop_caelestia

if [ -L "$CONFIG_DIR" ]; then
    unlink "$CONFIG_DIR"
fi
if [ -e "$CONFIG_BACKUP" ] || [ -L "$CONFIG_BACKUP" ]; then
    mv "$CONFIG_BACKUP" "$CONFIG_DIR"
fi

if [ -e "$WRAPPER" ] || [ -L "$WRAPPER" ]; then
    unlink "$WRAPPER"
fi
if [ -e "$WRAPPER_BACKUP" ] || [ -L "$WRAPPER_BACKUP" ]; then
    mv "$WRAPPER_BACKUP" "$WRAPPER"
fi

"$system_cli" shell -d

printf '\nRestored the system Caelestia installation.\n'
printf 'The local build remains cached under %s/build/local.\n' "$ROOT"
